version: "3.8"

services:
    frontend:
        image: familyresearchcouncil/washingtonstand:main
        deploy:
            replicas: 3
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.washingtonstand-prod.rule=Host(`www.washingtonstand.com`)"
                - "traefik.http.services.washingtonstand-prod.loadbalancer.server.port=3000"
            placement:
                constraints:
                    - node.role == worker
        command: npm run start
        networks:
            - traefik
            - default


networks:
    traefik:
        external: true
