version: "3.8"

services:
    frontend:
        image: familyresearchcouncil/washingtonstand:staging
        deploy:
            replicas: 1
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.washingtonstand-staging.rule=Host(`staging.washingtonstand.com`)"
                - "traefik.http.services.washingtonstand-staging.loadbalancer.server.port=3000"
            placement:
                constraints:
                    - node.role == worker
        command: npm run start
        networks:
            - traefik
            - default


networks:
    traefik:
        external: true
